### ISSUE TITLE
Magnet 魔链激活，加速下载

### ISSUE THREAD

**Issue by zhric** [zhric/zhric.github.io#18]
https://ric2cn.github.io/tools/magnet/mag.html 

 更新 magnet tracker 服务器，增加下载速度。每日更新服务器列表。

**Comment by ric2cn** [comment]
试了下 torrentkitty 上的种子能加速！

**Comment by ric2cn** [comment]
更新 magnet tracker 服务器，增加下载速度。每日更新服务器列表。

**Comment by ric2cn** [comment]
bt,magnet,tracker,魔法链接,加速下载
